name: Создание запроса на релиз
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  release-please:
    name: Работа Release-Please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.releases_created }}
      tag: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build-lib:
    name: Сборка плагина
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release == 'true' }}
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: nuget-${{ runner.os }}
      - run: gradlew jar -Pversion=${{ needs.release-please.outputs.version }}
        shell: cmd
      - uses: softprops/action-gh-release@v2
        with:
          files: ./build/libs/Tombstones-${{ needs.release-please.outputs.version }}.jar
          tag_name: ${{ needs.release-please.outputs.tag }}

  build-javadoc:
    name: Сборка JavaDoc
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release == 'true' }}
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: nuget-${{ runner.os }}
      - run: gradlew javadocJar
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/javadoc
      - uses: softprops/action-gh-release@v2
        with:
          files: ./build/libs/Tombstones-javadoc.jar
          tag_name: ${{ needs.release-please.outputs.tag }}

  deploy-javadoc:
    name: Развертка JavaDoc
    runs-on: ubuntu-latest
    needs: build-javadoc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
