name: Создание запроса на релиз
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release-please:
    name: Работа Release-Please
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.releases_created }}
      tag: ${{ steps.release.outputs.tag_name }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

  build-lib:
    name: Сборка плагина
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release == 'true' }}
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-lib-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-lib
      - run: gradlew jar -Pversion=${{ needs.release-please.outputs.version }}
        shell: cmd
      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          files: ./build/libs/Tombstones-${{ needs.release-please.outputs.version }}.jar
          tag_name: ${{ needs.release-please.outputs.tag }}
          token: ${{ secrets.RELEASE_TOKEN }}

  build-javadoc:
    name: Сборка JavaDoc
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release == 'true' }}
    needs: release-please
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-doc-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-doc
      - run: gradlew javadocJar
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/javadoc
      - uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        with:
          files: ./build/libs/Tombstones-javadoc.jar
          tag_name: ${{ needs.release-please.outputs.tag }}
          token: ${{ secrets.RELEASE_TOKEN }}

  deploy-javadoc:
    name: Развертка JavaDoc
    runs-on: ubuntu-latest
    needs: build-javadoc
    concurrency:
      group: "pages"
      cancel-in-progress: false
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
